//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicStudentManagementSystem.UI.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studentdetail
    {
        public int id { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> StudentBD { get; set; }
        public Nullable<int> Age { get; set; }
        public string CourseName { get; set; }
        public string PhoneNumber { get; set; }
        public string sex { get; set; }
    }
}
